Default: &defaults
  user: hanabidb
  password: hanabidb
  host: localhost
  port: 5432
  database: hanabi
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Hanabi_test
  <<: *defaults

Staging:
  database: Hanabi_staging
  poolsize: 100
  <<: *defaults

Production:
  database: hanabi
  poolsize: 20
  <<: *defaults
