Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://localhost:3000"
  approot: "http://158.130.105.182:3000"
  copyright: 
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://158.130.109.212:3000"
  <<: *defaults
